### ISSUE TITLE
Not work with 24-bit PNG photos?

### ISSUE THREAD

**Issue by damphat** [datvm/PNG2ICOjs#1]
**I can't open the output file in any of my photo editors, except `Google Chrome`.**

Did you forget to set the `bits per pixel` or something?

## Reproduction:

1. Used this 24-bits photo as input
![input-256-24](https://user-images.githubusercontent.com/677382/167413163-1481fbee-16dc-4ed0-bf38-6f48339ea0c4.png)

2. Convert to ICO file using default parameters

https://png2icojs.lukevo.com/

4. Open the output ICO in `Microsoft Paint` or `Photo Viewer`
![image](https://user-images.githubusercontent.com/677382/167408545-ca29bd8f-e7d7-48ee-a864-536ce1fefcfa.png)

_**Note: It happened to 24-bit photos only, I have tried with 32-bit input, it worked fine ✌️**_

**Comment by datvm** [comment]
Hi @damphat ,

Thank you so much for bringing this issue to my attention. I have investigated the issue but it looks like it's Windows Photos' limitation.

My library has a `bpp` option that you can use to set it to whatever value you want. It's true that at the web app https://png2icojs.lukevo.com/, I didn't set the BitsPerPixel information so it is 0. However according to the information available:

> The bits per pixel might be set to zero, but can be inferred from the other data; specifically, if the bitmap is not PNG compressed, then the bits per pixel can be calculated based on the length of the bitmap data relative to the size of the image. If the bitmap is PNG compressed, the bits per pixel are stored within the PNG data. It is unknown if the various Windows operating system versions contain logic to infer the bit depth for all possibilities if this value is set to zero.

I also tried setting the BPP manually to 24 but the file is still corrupted to Windows Photos.

I also tried putting that file into various online converter like https://cloudconvert.com/png-to-ico or https://convertio.co/png-ico/. The output is similar to my code and the files can be viewed in browsers like Chrome but NOT in MS Photos. Editors like https://redketchup.io/icon-editor can also open/edit the files just fine.

I suspect this cannot be fixed as even with correct BPP information, Windows still cannot open it anyway. If you find out what the real issue is, please tell me and I will try fixing it. In the meantime, it's probably better to re-draw the image in a canvas and convert it to 32bpp.
