### ISSUE TITLE
How to use the blob "resultBlob1"

### ISSUE THREAD

**Issue by ANiLeJodea** [datvm/PNG2ICOjs#2]
Sorry if it is a bit of a noy okay question, but how to use "resultBlob1" in the code after the conversion? I mean... This blob contains lot of images. How to add ut as a source of img tag, for example?

**Comment by datvm** [comment]
@ANiLeJodea Hi no worry, the Blob is an `image/x-icon` Blob, basically a presentation of ICON file. So you can create an URL and [save it](https://stackoverflow.com/a/25911218/653457) or use that URL to display it using a `<img />` tag. See [example on how to save that file from the demo app](https://github.com/datvm/PNG2ICOjs/blob/fb676580040d4ab09d5a8a692c489af4258d11b9/js/convert.js#L24C11-L24C11). Instead of fetching that URL to download, you can set it to a `<img />`.

> This blob contains lot of images

It does but that's the point of ICO file. It's basically a container of PNG files (it's more than that but in simple term let's just say that). Browser or image apps get to decide what to do or what to display.
